### ISSUE TITLE
Great documentation & thanks for sharing!

### ISSUE THREAD

**Issue by harryhaaren** [arthurggordon/emb-rust#1]
Hey @arthurggordon,

Just a note of thanks, having this repo & being able to run the commands is very helpful to quickly get setup on a new board/env. Its just the jump-start that saves hours of messing with some commands that I'm not quite familiar with at this point.

Thanks for documenting so clearly, and sharing your resulting code! Regards, -Harry

**Comment by arthurggordon** [comment]
Hi @harryhaaren,

Thank you for your message, I am pleased to hear that the project has helped at least one other person!
Enjoy your embedded Rust journey - Arthur

**Comment by harryhaaren** [comment]
Cheers, I'll close this issue to remove it from the list of open issues.
